### ISSUE TITLE
Clean Object 这个功能是做什么用的？点击后没有任何反应

### ISSUE THREAD

**Issue by LiJT** [BakaAkari/Fix_Quixel_Bridge_Addon#5]
感谢作者！！能否答疑解惑一下

**Comment by BakaAkari** [comment]
Sorry, 我很少看Issues

是我在使用Hardops, M3T制作模型的时候, 这两个插件会自动给模型标记一些seam, sharp之类的信息
这个功能是一键清理这些信息用的
